package GBG::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'GBG::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=bob_gbg',
        user => '',
        password => '',
    }
);

=head1 NAME

GBG::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<GBG>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<GBG::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.29

=head1 AUTHOR

Bob Waker

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
